grails-app/domain/bigjrepository/Product.groovy
package bigjrepository

class Product {

    String name
    String color
    String size
    String description
    // String stock_number
    // int quantity
    double price
    String photo_extension
    Date dateCreated
    Date lastUpdated
    Date last
    Boolean hasIncreasedPrice
    static belongsTo = [subCategory: SubCategory]
    Type type


    static constraints = {
        photo_extension nullable: true
        last nullable: true
        subCategory nullable: true
        type nullable: true
        hasIncreasedPrice nullable: true
    }

    def checkIncreasePrice(double newPrice) {
        if (this.getPersistentValue('price') == newPrice) {
            return
        }
        if (this.getPersistentValue('price') < newPrice) {
            return true
        }
        return false
    }

    def removeFromSubCategory() {
        if (this.subCategory != null) {
            def sub = SubCategory.get(this.subCategory.id)
            sub.removeFromProducts(this)
            sub.save flush: true
        }
    }

    def removeFromWholesale() {
        def wholesalesProducts = WholesaleProduct.createCriteria().list {
            product {
                ilike("name", this.name)
            }
        }

        if (wholesalesProducts != null) {
            for (product in wholesalesProducts) {
                product.transaction.removeFromWholesaleProducts(product)
                product.delete flush: true
            }
        }

    }

    def removeFromStorage() {
        def storageProducts = Storage.createCriteria().list {
            product {
                ilike("name", this.name)
            }
        }

        if (storageProducts != null) {
            for (product in storageProducts) {
                product.delete flush: true
            }
        }
    }

    def removeFromPurchaseOrder() {
        def purchaseProducts = PurchaseOrderProduct.createCriteria().list {
            product {
                ilike("name", this.name)
            }
        }

        if (purchaseProducts != null) {
            for (product in purchaseProducts) {
                product.transaction.removeFromOrderedProducts(product)
                product.delete flush: true
            }
        }
    }

}

grails-app/controllers/bigjrepository/ProductController.groovy
package bigjrepository


import static org.springframework.http.HttpStatus.*
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.web.multipart.commons.CommonsMultipartFile;
import grails.transaction.Transactional
import grails.plugin.springsecurity.annotation.Secured

@Secured(['permitAll'])
@Transactional(readOnly = true)
class ProductController {

    static responseFormats = ['json', 'xml']
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        // params.max = Math.min(max ?: 10, 100)
        respond Product.list(params), [status: OK]
    }

    def show(Product productInstance) {
        respond productInstance
    }

    @Transactional
    def save(Product productInstance) {
        if (productInstance == null) {
            render status: NOT_FOUND
            return
        }

        productInstance.validate()
        if (productInstance.hasErrors()) {
            render status: NOT_ACCEPTABLE
            return
        }
        productInstance.save flush: true
        // productInstance.last = productInstance.lastUpdated
        // productInstance.save flush:true
        respond productInstance, [status: CREATED]
    }

    @Transactional
    def update(Product productInstance) {
        def product1 = Product.get(productInstance.id)
        if (productInstance == null) {
            render status: NOT_FOUND
            return
        }

        productInstance.validate()
        if (productInstance.hasErrors()) {
            render status: NOT_ACCEPTABLE
            return
        }
        productInstance.last = productInstance.lastUpdated
        productInstance.hasIncreasedPrice = product1.checkIncreasePrice(productInstance.price)
        productInstance.save flush: true
        respond productInstance, [status: OK]
    }

    @Transactional
    def delete(Product productInstance) {

        if (productInstance == null) {
            render status: NOT_FOUND
            return
        }
        def file = new File(grailsApplication.config.images.location.toString() + productInstance.id + "." + productInstance.photo_extension)
        if (file != null) {
            file.delete()
        }

        productInstance.removeFromSubCategory()
        productInstance.removeFromWholesale()
        productInstance.removeFromStorage()
        productInstance.removeFromPurchaseOrder()
        productInstance.delete flush: true
        render status: NO_CONTENT
    }

    def upload() {
        def file = request.getFile('myFile')
        if (file == null) {
            render status: NOT_FOUND
            return
        } else {
            def lastInserted = Product.find("from Product order by id desc")
            def product = Product.get(lastInserted.id)

            if (file.contentType == "image/jpeg") {
                product.photo_extension = 'jpg'
            } else {
                product.photo_extension = 'png'
            }
            product.save flush: true
            def filename = grailsApplication.config.images.location.toString() + lastInserted.id + '.' + product.photo_extension
            file.transferTo(new File(filename))
            render(status: 200, text: "OK")
        }
    }

    def editUpload() {
        def file = request.getFile('myFile')
        if (file == null) {
            render status: NOT_FOUND
            return
        } else {
            def product = Product.get(params.id)

            if (file.contentType == "image/jpeg") {
                product.photo_extension = 'jpg'
            } else {
                product.photo_extension = 'png'
            }
            product.save flush: true
            def filename = grailsApplication.config.images.location.toString() + params.id + '.' + product.photo_extension
            file.transferTo(new File(filename))
            render(status: 200, text: "OK")
        }
    }

}

grails-app/views/product/_form.gsp
<%@ page import="bigjrepository.Product" %>



<div class="fieldcontain ${hasErrors(bean: productInstance, field: 'color', 'error')} required">
	<label for="color">
		<g:message code="product.color.label" default="Color" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="color" required="" value="${productInstance?.color}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: productInstance, field: 'description', 'error')} required">
	<label for="description">
		<g:message code="product.description.label" default="Description" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="description" required="" value="${productInstance?.description}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: productInstance, field: 'item_name', 'error')} required">
	<label for="item_name">
		<g:message code="product.item_name.label" default="Itemname" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="item_name" required="" value="${productInstance?.item_name}"/>

</div>

%{-- <div class="fieldcontain ${hasErrors(bean: productInstance, field: 'photo_file_name', 'error')} required">
	<label for="photo_file_name">
		<g:message code="product.photo_file_name.label" default="Photofilename" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="photo_file_name" required="" value="${productInstance?.photo_file_name}"/>

</div> --}%
%{-- <g:uploadForm action="upload">
	<fieldset class="form">
		Photo: --}%
        
%{-- 	</fieldset>
</g:uploadForm> --}%

<div class="fieldcontain ${hasErrors(bean: productInstance, field: 'price', 'error')} required">
	<label for="price">
		<g:message code="product.price.label" default="Price" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="price" value="${fieldValue(bean: productInstance, field: 'price')}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: productInstance, field: 'quantity', 'error')} required">
	<label for="quantity">
		<g:message code="product.quantity.label" default="Quantity" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="quantity" type="number" value="${productInstance.quantity}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: productInstance, field: 'size', 'error')} required">
	<label for="size">
		<g:message code="product.size.label" default="Size" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="size" required="" value="${productInstance?.size}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: productInstance, field: 'stock_number', 'error')} required">
	<label for="stock_number">
		<g:message code="product.stock_number.label" default="Stocknumber" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="stock_number" required="" value="${productInstance?.stock_number}"/>

</div>

<input type="file" name="file" />

grails-app/views/product/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'product.label', default: 'Product')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-product" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-product" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${productInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${productInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form enctype="multipart/form-data" url="[resource:productInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/product/edit.gsp
<%@ page import="bigjrepository.Product" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'product.label', default: 'Product')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-product" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-product" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${productInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${productInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:productInstance, action:'update']" method="PUT" enctype="multipart/form-data">
				<g:hiddenField name="version" value="${productInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<div>
					<g:if test="${productInstance?.photo_file_name}">
					<img src="/BigJRepository/images/${productInstance.id}.${productInstance.photo_file_name}" width="200">
					</g:if>
					<g:else>
					    <img src="/BigJRepository/images/default.jpg" width="200">
					</g:else>
				</div>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/product/index.gsp
<%@ page import="bigjrepository.Product" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'product.label', default: 'Product')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-product" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-product" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<fieldset class="form">
			    <g:form action="index" method="GET">
			        <div class="fieldcontain">
			            <label for="query">Search for products:</label>

			            <g:select name="characteristic" value="${params.characteristic}" from="${attributes}" optionKey="value" optionValue="key">
						</g:select>
						%{--<g:textField name="foo" value="${params.foo}"/>--}%
			            <g:textField name="query" value="${params.query}"/>

			        </div>
			    </g:form>
			</fieldset>
			<table>
			<thead>
					<tr>
						<td>Picture</td>
						<g:sortableColumn property="color" title="${message(code: 'product.color.label', default: 'Color')}" />
					
						<g:sortableColumn property="description" title="${message(code: 'product.description.label', default: 'Description')}" />
					
						<g:sortableColumn property="item_name" title="${message(code: 'product.item_name.label', default: 'Itemname')}" />
					
						<g:sortableColumn property="photo_file_name" title="${message(code: 'product.photo_file_name.label', default: 'Photofilename')}" />
					
						<g:sortableColumn property="price" title="${message(code: 'product.price.label', default: 'Price')}" />
					
						<g:sortableColumn property="quantity" title="${message(code: 'product.quantity.label', default: 'Quantity')}" />

						<g:sortableColumn property="size" title="${message(code: 'product.size.label', default: 'Size')}" />

						<g:sortableColumn property="stock_number" title="${message(code: 'product.stock_number.label', default: 'Stock Number')}" />

					
					</tr>
				</thead>
				<tbody>
				<g:each in="${productInstanceList}" status="i" var="productInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td>
							<g:if test="${productInstance?.photo_file_name}">
								<img src="/BigJRepository/images/${productInstance.id}.${productInstance.photo_file_name}" width="100">
							</g:if>
							<g:else>
							    <img src="/BigJRepository/images/default.jpg" width="200">
							</g:else>
						</td>
						<td><g:link action="show" id="${productInstance.id}">${fieldValue(bean: productInstance, field: "color")}</g:link></td>
					
						<td>${fieldValue(bean: productInstance, field: "description")}</td>
					
						<td>${fieldValue(bean: productInstance, field: "item_name")}</td>
					
						<td>${fieldValue(bean: productInstance, field: "photo_file_name")}</td>
					
						<td>${fieldValue(bean: productInstance, field: "price")}</td>
					
						<td>${fieldValue(bean: productInstance, field: "quantity")}</td>

						<td>${fieldValue(bean: productInstance, field: "size")}</td>

						<td>${fieldValue(bean: productInstance, field: "stock_number")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${productInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/product/show.gsp
<%@ page import="bigjrepository.Product" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'product.label', default: 'Product')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-product" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-product" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list product">
				<g:if test="${productInstance?.photo_file_name}">
					<img src="/BigJRepository/images/${productInstance.id}.${productInstance.photo_file_name}" width="200">
				</g:if>
				<g:else>
				    <img src="/BigJRepository/images/default.jpg" width="200">
				</g:else>

				<g:if test="${productInstance?.color}">
				<li class="fieldcontain">
					<span id="color-label" class="property-label"><g:message code="product.color.label" default="Color" /></span>
					
						<span class="property-value" aria-labelledby="color-label"><g:fieldValue bean="${productInstance}" field="color"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${productInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="product.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${productInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${productInstance?.item_name}">
				<li class="fieldcontain">
					<span id="item_name-label" class="property-label"><g:message code="product.item_name.label" default="Itemname" /></span>
					
						<span class="property-value" aria-labelledby="item_name-label"><g:fieldValue bean="${productInstance}" field="item_name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${productInstance?.photo_file_name}">
				<li class="fieldcontain">
					<span id="photo_file_name-label" class="property-label"><g:message code="product.photo_file_name.label" default="Photofilename" /></span>
					
						<span class="property-value" aria-labelledby="photo_file_name-label"><g:fieldValue bean="${productInstance}" field="photo_file_name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${productInstance?.price}">
				<li class="fieldcontain">
					<span id="price-label" class="property-label"><g:message code="product.price.label" default="Price" /></span>
					
						<span class="property-value" aria-labelledby="price-label"><g:fieldValue bean="${productInstance}" field="price"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${productInstance?.quantity}">
				<li class="fieldcontain">
					<span id="quantity-label" class="property-label"><g:message code="product.quantity.label" default="Quantity" /></span>
					
						<span class="property-value" aria-labelledby="quantity-label"><g:fieldValue bean="${productInstance}" field="quantity"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${productInstance?.size}">
				<li class="fieldcontain">
					<span id="size-label" class="property-label"><g:message code="product.size.label" default="Size" /></span>
					
						<span class="property-value" aria-labelledby="size-label"><g:fieldValue bean="${productInstance}" field="size"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${productInstance?.stock_number}">
				<li class="fieldcontain">
					<span id="stock_number-label" class="property-label"><g:message code="product.stock_number.label" default="Stocknumber" /></span>
					
						<span class="property-value" aria-labelledby="stock_number-label"><g:fieldValue bean="${productInstance}" field="stock_number"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:productInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${productInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>